add validation in compile-aar

diff --git a/compile-aar b/compile-aar
--- a/compile-aar
+++ b/compile-aar
@@ -1,6 +1,18 @@
 #!/bin/bash
 set -e
 
+if [[ ! "$VLC_ANDROID_VERSION" =~ ^[0-9\.]+$ ]]
+then
+    echo "Invalid vlc android version: $VLC_ANDROID_VERSION"
+    exit 1
+fi
+
+if [[ ! "$VERSION" =~ ^[0-9\.]+$ ]]
+then
+    echo "Skip building for vlc-android-sdk: $VERSION"
+    exit 1
+fi
+
 PROJECT_DIR=`pwd`
 ANDROID_NDK="$HOME"/ndk
 rm -rf "$ANDROID_NDK"
